### ISSUE TITLE
Add requests for managing User Identity Pool

### ISSUE THREAD

**Issue by a5170836** [tableau/tableau-postman#119]
In Tableau server 2023.1 we release user identity pool feature.
I created a PR to add new requests for managing User Identity Pool.
[Collections PR link](https://www.postman.com/speeding-zodiac-460346/workspace/my-workspace/pull-request/74332704-ad5c-4f7b-9a87-a3079223c8ee?workspace=29751a01-711e-4513-8d6e-24ce7e88b0d7)

[Environments PR link](https://www.postman.com/speeding-zodiac-460346/workspace/my-workspace/pull-request/80524180-70fc-4854-bbaa-5585ae1860c7?workspace=29751a01-711e-4513-8d6e-24ce7e88b0d7)

**Comment by dzucker-tab** [comment]
Done!
